/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    Contact: typeof import('./components/Contact.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Help: typeof import('./components/Help.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    LineChart: typeof import('./components/LineChart.vue')['default']
    ManagementTable: typeof import('./components/ManagementTable.vue')['default']
    MonthlyTable: typeof import('./components/MonthlyTable.vue')['default']
    ParameterTable: typeof import('./components/ParameterTable.vue')['default']
    PieChart: typeof import('./components/PieChart.vue')['default']
    ResultsTable: typeof import('./components/ResultsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YearlyTable: typeof import('./components/YearlyTable.vue')['default']
    YieldsTable: typeof import('./components/YieldsTable.vue')['default']
  }
}
